### ISSUE TITLE
Support for CITEXT extension types

### ISSUE THREAD

**Issue by MaikuMori** [jackc/pgtype#1]
Would be nice if `pgx` supported [CITEXT ](https://www.postgresql.org/docs/current/citext.html)extension which is often used for email fields.

I believe we just need to alias them to TEXT field.

I've currently added it like this:

```go
conn.ConnInfo.RegisterDataType(pgtype.DataType{
	Value: &pgtype.Text{},
	Name:  "citext",
	OID:   16393,
})
```

And it seems to work, but I haven't done extensive testing.

**Comment by jackc** [comment]
That will work for your particular database instance, but it will not work in the general case. The problem is that since it is an extension it does not have a stable OID (hstore has the same problem). If the type needs to be reliably registered then it is necessary to look in `pg_catalog` at connect time and lookup the OID by type name.

That said, for `citext` registering the type shouldn't usually be necessary since the binary format doesn't provide any advantages over the text format. It should work and be mapped to `pgtype.GenericText` by default.

**Comment by MaikuMori** [comment]
Ah I see. I got the unknown OID error message when I was trying to use it w/o special type. I can check again. Thanks for the heads up regarding the changing OID.

If I still get the error message, I'll post the exact text here.

**Comment by MaikuMori** [comment]
It does seem to work now w/o registering data type. Thanks.
