### ISSUE TITLE
scanning into BinaryDecoder ignores source OID

### ISSUE THREAD

**Issue by mdelah** [jackc/pgtype#139]
The following program allows a encoded integer to be incorrectly interpreted as text with no error produced (it prints `got: "\x00\x00\x00{"`):
```
package main

import (
        "golang.org/x/net/context"
        "fmt"
        "os"

        "github.com/jackc/pgtype"
        "github.com/jackc/pgx/v4"
)

func main() {
        ctx := context.Background()
        conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
        if err != nil {
                panic(err)
        }
        var text pgtype.Text
        if err := conn.QueryRow(ctx, "select 123").Scan(&text); err != nil {
                panic(err)
        }
        fmt.Printf("got: %q\n", text.String)
}
```
I understand that in this specific example scanning into a `string` or `*string` would be more typical, but I ask more in the context of implementing `BinaryDecoder` on custom types. It would seem that implementing `DecodeBinary` directly on the type being scanned into is unsafe, because it makes `PlanScan` return `scanPlanDstBinaryDecoder` which has no means of verifying whether the source OID is what's expected. Can `scanPlanDstBinaryDecoder` be leveraged correctly?

**Comment by jackc** [comment]
This is true, but it's not specific to `BinaryDecoder`. The same issue is present with `TextDecoder`, it's just much less likely that the text format of one type would be incorrectly and silently decoded into another.

When using a type that implements decoding the caller is responsible for ensuring it is a compatible type. It would be very difficult to do otherwise. If the decode function received an argument of the value's OID that would allow a type to check for a compatible OID. But unfortunately, that isn't enough. Any type that is not part of the core PostgreSQL like `hstore`, PostGIS types, and user defined types do not have fixed OIDs. So type handlers for those cannot check an OID. But even core types shouldn't reject unknown OIDs. Otherwise those types would reject decoding [domain types](https://www.postgresql.org/docs/current/sql-createdomain.html).

I *am* considering changing the interface for decoding in a future release to something that includes the OID like this:

```go
DecodeResult(ci *ConnInfo, oid uint32, format int16, src []byte) error
```

But as I mentioned above I don't think that a decoder actually could filter on OID in most circumstances.

**Comment by mdelah** [comment]
Understood, thanks @jackc.

In my case I have data types registered for all the non-builtin OIDs I care about in the `ConnInfo`, so my decoders can simply look up the OID there and see if they can type-assert the `Value` to something they recognise. This is somewhat nicer than `scanPlanDataTypeAssignTo` because it means I can scan directly into the destination variable without the intermediate `Value` representation (and for reasons that are probably more specific to my project, there may multiple Go types corresponding to a particular OID and it would be impractical to write a `DataType` that can `AssignTo` all of them). Thus I would welcome the interface change above (and something symmetric for encoding would be good too). But I'll just be extra careful for now.

Thanks again for the great library!
