### ISSUE TITLE
Inet column is scanned as text even when it's binary

### ISSUE THREAD

**Issue by dreamscached** [jackc/pgtype#140]
I was trying to implement a 'first or create' logic with GORM that involved Inet column, and it kept having errors on attempt to scan.

In debugging process I've tried using `dst.DecodeBinary` (instead of [DecodeText](https://github.com/jackc/pgtype/blob/e95ebc02d9bcbf851891deeb7566df84218dc44f/inet.go#L249)) and it worked.

Could it be a bug/typo?

**Comment by jackc** [comment]
I think something else is going on. pgx doesn't have any guarantee that a `database/sql` `Scanner` supports the PostgreSQL binary format. In most cases they would not. Because of this values are generally converted to the text format before being passed to `Scan`.

See:

https://github.com/jackc/pgtype/blob/75446032b914bb0be5e07da29c976034c0a666cf/pgtype.go#L527
and
https://github.com/jackc/pgtype/blob/75446032b914bb0be5e07da29c976034c0a666cf/database_sql.go#L8

Scan being called with a binary formatted value is the underlying problem IMO.

**Comment by dreamscached** [comment]
Okay, understood.
