### ISSUE TITLE
HSTORE/TEXT empty strings stored as null

### ISSUE THREAD

**Issue by Bysmyyr** [jackc/pgtype#33]
Hi, I ended up with this problem::

```package main

import (
    "fmt"
    "github.com/jackc/pgtype"
)

func main() {
    var buf []byte
    t := pgtype.Text{"", pgtype.Present}

    res, _ := t.EncodeText(nil, buf)

    if res == nil {
        fmt.Print("This should not happen")
    }
}
```

We found that when we were storing empty strings as values to the hstore. They ended up to be stored as nils.  Basically, the problem is in `return append(buf, src.String...), nil` the `src.String...` when it is `""...` which evaluates to nothing, e.g.` return append(buf)` which is in that case nil.

**Comment by jackc** [comment]
Hmm... That's interesting. In normal usage that should never happen because `EncodeText` is never called with a `nil` buffer. The buffer is already initialized.

I suppose it's not a technically documented requirement though -- though it is implied by the semantics of `append`. I lean toward it being the caller's responsibility rather than every type have to account for being passed a `nil` buffer. `Hstore` `EncodeText` was violating that requirement but other types with similar usage like `TextArray` were handling it correctly.

I just pushed a fix to master for Hstore. See if that resolves the issue for you.

**Comment by Bysmyyr** [comment]
Yes, thanks a lot, now it works!

**Comment by Bysmyyr** [comment]
Any plans to make a release including this?
