### ISSUE TITLE
Is there any reason to prefer pgtype types to standard ones?

### ISSUE THREAD

**Issue by TwiceII** [jackc/pgtype#44]
Hi, first of all, thanks for your awesome libraries! 
I didn't know where exactly should I post this question, so I apologize in advance, feel free to close this topic.

My question is: are there any benefits from using pgtype primitive types such as Varchar, Bool, Timestamp etc. compared to standard Go types like string, bool, Time? Any performance gains? 

It's much more cumbersome to use pgtype types in a struct, for example:
```
type Item {
	MetaCreatedAt           pgtype.Timestamptz     `db:"meta_created_at"`
        CurrencyCode             pgtype.Varchar              `db:"currency_code"`
...}
```
especially when trying to create structs with fields inline. Also, from now on you must use `.Get()` to interact with the rest of your Go codebase. 
pgtype types are very useful when you need some postgres specific types like hstore, jsonb etc, but is it worth the hussle for primitive types?

**Comment by jackc** [comment]
The primary use for these types in application code is to allow for null values. They also differ from `sql.Null*` types in that the zero value is an unset / undefined case rather than representing null. This can be useful for partially populating a row struct and distinguishing between a column that was not read vs a column that is null.

But if you do not need null or undefined then you should prefer the standard Go types. The performance difference will be negligible in almost all cases.

**Comment by TwiceII** [comment]
I see. I guess this line in README.md:
"These types support the binary format for enhanced performance with pgx" kinda confused me. Thanks, I will close it now.

**Comment by jackc** [comment]
Ah. I see how that could be confusing. They can be used directly but pgx automatically uses them internally when when scanning to standard Go types.
