### ISSUE TITLE
Inefficiency when scanning some types

### ISSUE THREAD

**Issue by jaltavilla** [jackc/pgtype#8]
We are investigating switching from lib/pq to pgx to see if it improves performance. I'm encountering an issue where scanning into a type results in an unecessary call to Value and Scan. In this specific case it is the uuid type in https://github.com/pborman/uuid. This library defines a uuid that implements the sql.Scanner interface. However, I think this would happen for any type that implements the sql.Scanner interface, but not the pgtype.TextDecoder or pgtype.BinaryDecoder interface.

The problem happens in https://github.com/jackc/pgtype/blob/d3b475212c250949fca8b1336bc38911e5cef2ed/pgtype.go#L337. The destination type doesn't implement either decoder interface, but there is a DataType for this oid. This results in DecodeBinary being called on the local value; a pgtype.UUID. Afterwards, since the destination type (a pboreman/uuid) implements Scanner, the uuid is then encoded to the text format in DatabaseSQLValue, and then Scanned into the dest object. This seems wasteful, when the alternative path of AssignTo would have worked.

I can't make the pboreman/uuid type implement the BinaryDecoder interface, nor can I stop it from implementing the Scanner interface. I could make a new type that wraps the uuid, but we have hundreds of functions (and their tests), that would have to be changed. In addition to the cost involved, failing to convert a variable wouldn't be caught by the compiler, it would silently be more expensive than necessary.

I'm wondering if I missed something, and there is a way to avoid this spurious work? If not, can the logic of Scan be altered to avoid this? For example, could AssignTo be tried first, and on an error it tries to value and scan if possible. Alternatively, maybe the DataType could contain a flag of whether to try this path or not.

Thanks.

**Comment by jackc** [comment]
That's a tricky case. The reason for the decode and then encode back to text for scan is it is assumed most database/sql scanners do not expect the PostgreSQL binary format. For example, this is the case when using https://github.com/shopspring/decimal. But that creates extra work for https://github.com/pborman/uuid.

> I'm wondering if I missed something, and there is a way to avoid this spurious work? If not, can the logic of Scan be altered to avoid this? For example, could AssignTo be tried first, and on an error it tries to value and scan if possible. Alternatively, maybe the DataType could contain a flag of whether to try this path or not.

In some cases `AssignTo` could correctly be called first, but that mean a scanner that was implemented on a basic type that `AssignTo` understood would never be called. e.g.

```go
type Foo string

func (f *Foo) Scan(src interface{}) error {
	// unreachable
}
```

... stares at the code a bit longer ...

I think there is a way to do what you want. `pgtype.UUID` implements `database/sql/driver.Valuer`. This is what actually does the work in `DatabaseSQLValue()`

```go
func (src UUID) Value() (driver.Value, error) {
	return EncodeValueText(src)
}
```

And again it is implemented in terms of strings / the text protocol because that is typically what scanners expect. But since you know that you will always be scanning into something that accepts the binary format you could change that.

If you made your own UUID type based on `pgtype.UUID` and changed the `Value()` method to something like:

```go
func (src UUID) Value() (driver.Value, error) {
	return src.Bytes[:]
}
```

Then you could need to register your new type in the ConnInfo to override the default UUID mapping and any scans would use the new path.

I think this would do what you want.

**Comment by jackc** [comment]
Hmm... I wonder if it would be safe to just make that change in `pgtype.UUID`.

```go
func (src UUID) Value() (driver.Value, error) {
	return src.Bytes[:]
} 
```

I looked at several Go UUID implementations and they all handle `[]byte` where len is 16 correctly...

**Comment by jaltavilla** [comment]
I tested out your suggestion, and it worked properly in all of my tests.  Thanks for the quick response.
